[tool.poetry]
name = "foggy_training"
version = "0.1.15"
description = ""
authors = ["JanDiers <jan.diers@uni-jena.de>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.5.1"
numpy = "^1.23.4"
attrs = "^22.1.0"

scikit-learn = "^1.1.3"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
mkdocs = "^1.4.1"
mkdocs-material = "^8.5.7"
mkdocstrings = {extras = ["python"], version = "^0.19.0"}
torch = "^1.12.1"
torchvision = "^0.13.1"
torchaudio = "^0.12.1"
pytorch-lightning = "^1.7.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
