[tool.poetry]
name = "i-mongodb"
version = "1.0.1"
description = "Customized connector to MongoDB"
authors = ["Jason Romano <aracnid@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/aracnid/i-mongodb"
keywords = ["python", "mongodb"]
packages = [{include = "i_mongodb"}]

[tool.poetry.dependencies]
python = "^3.10"
aracnid_logger = "^1.0"
dnspython = "^1.16"
pymongo = {version = "^4.3", extras = ["srv"]}
python-dateutil = "^2.8"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15"
pytest = "^7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-p no:warnings"
log_cli = true
log_cli_level = "DEBUG"
