[tool.poetry]
name = "pypipr"
version = "0.1.36"
description = "The Python Package Index Project"
authors = ["ufiapjj <ufiapjj@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytz = "^2022.4"
getch = { version = "^1.0", markers = "platform_system == 'Linux'" }
colorama = "^0.4.5"
lxml = "^4.7.1"
cssselect = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
