[tool.poetry]
name = "burner"
description = "Script to interact with SimSMS's website."

version = "0.7.0"

authors = ["Aidan <ramadan8@riseup.net>"]

readme = "README.md"
license = "MIT"

repository = "https://github.com/ramadan8/Burner"
packages = [{include = "burner"}]

keywords = ["phone", "burner", "sms", "simsms"]

classifiers = [
    "Topic :: Communications :: Internet Phone",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]

[tool.poetry.dependencies]
python = "^3.8"
peewee = "^3.15.3"
requests = "^2.28.1"
click = "^8.1.3"
beautifulsoup4 = "^4.11.1"
phonenumbers = "^8.12.57"

[tool.poetry.scripts]
burner = "burner.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
