[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "py_it_crypto"
version = "1.0.5"
dependencies = [
    "jwcrypto~=1.4.2",
    "pyOpenSSL~=22.1.0"
]

authors = [
  { name="Jonas Hagg" },
]
description = "E2EE for the inverse transparency toolchain"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]