[tool.poetry]
name = "eHelply-Microservice-Library"
version = "1.12.2"
description = ""
authors = ["Shawn Clake <shawn.clake@gmail.com>"]
readme = "readme.md"
homepage = "https://ehelply.com"

[tool.poetry.dependencies]
python = "~3.10"
ehelply-bootstrapper = "^0.18.0"
ehelply-generator = "^0.1.2"
ehelply-updater = "^0.2.0"
Jinja2 = "^3.1.1"
pytest-mock = "^3.7.0"
coverage = "^6.3.2"
ehelply-python-experimental-sdk = "^1.1.112"
ehelply-python-sdk = "^1.1.112"

[tool.poetry.scripts]
ehelply_microservice_library = 'ehelply_microservice_library.cli.self_cli:cli_main'

[tool.poetry.dev-dependencies]
pytest = "^6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
