[tool.poetry]
name = "wf-test"
version = "0.0.0"
description = "Test Workflows."
authors = ["Harshad Hegde <hhegde@lbl.gov>"]
readme = "README.md"
packages = [{include = "src/wf_test"}]

[tool.poetry.dependencies]
python = "^3.9"
tox = "^3.27.0"
pytest = "^7.2.0"
sphinx = {version = "^5.3.0", extras = ["docs"]}
sphinx-autodoc-typehints = {version = "^1.19.4", extras = ["docs"]}
sphinx-click = {version = "^4.3.0", extras = ["docs"]}
myst-parser = {version = "^0.18.1", extras = ["docs"]}
furo = {version = "^2022.9.29", extras = ["docs"]}

[tool.poetry.extras]
docs = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-click",
    "myst-parser",
    "furo"
    ]
    
[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
