[tool.poetry]
name = "datamonk-utils"
version = "1.0.0"
description = ""
authors = ["Vit Mrnavek <vit.mrnavek@datamonk.cz>"]
packages = [
    { include = "datamonk/utils" }
]
[tool.poetry.dependencies]
python = ">=3.9.0,<3.10.0"
pandas = "^1.4.3"
redmail = "^0.4.2"
slack-logger = "^0.3.1"
python-dotenv = "^0.21.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
