[tool.poetry]
name = "klogin"
version = "0.6.1"
description = ""
authors = ["Logi Leifsson <logi@genuitysci.com>"]
readme = "README.md"
include = ["profiles"]

[tool.poetry.scripts]
klogin = 'klogin:main'

[tool.poetry.dependencies]
python = ">=3.8,<3.12"

[tool.poetry.group.dev.dependencies]
ipython = "^8.5.0"
pyinstaller = "^5.6.1"

[[tool.poetry.source]]
name = "gitlab"
url = "https://gitlab.com/api/v4/projects/40598779/packages/pypi"
default = false
secondary = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
