# This environment table contains the necessary setup that must be done before running the application
[environment]
smtp.host = "SS_SMTP_HOST"
ib.sftp.username = "SS_IB_SFTP_USER"
ib.sftp.password = "SS_IB_SFTP_PWD"
maeu.api_key = "SS_MAEU_API_KEY"
directory.data = ""     # 'C:\Users\alex.cheng\Documents\seaschedule\data'
directory.log = ""      # 'C:\Users\alex.cheng\Documents\seaschedule\log'


[email]
from = "donotreply@kuehne-nagel.com"
to = "alex.cheng@kuehne-nagel.com"
cc = ""
subject = "Maersk Vessel Schedules Automation"
body = """
<html>
  <head>
  </head>
  <body>
    <p style="font-family: Arial, Helvetica, Sans-serif; font-size: 12px;">
        Dear users,<br>
        <br>
        $result_line<br>
        <br>
        Log Summary:<br>
        <br>
        $log_summary
        <br>
        Best Regards,<br>
        Robot
    </p>
  </body>
</html>
"""


[ib]
sftp.enable = true
sftp.host = "mft-test.kuehne-nagel.com"
sftp.port = 22
sftp.remote_directory = "/pub/outbound/APITDUX/APITDUX-00"


[logging]
logger = "seaschedule"
filename = "seaschedule_execution_{}.log"
level = 20  # 50 = CRITICAL, 40 = ERROR, 30 = WARNING, 20 = INFO, 10 = DEBUG
format = "%(asctime)s\t%(levelname)s\t%(filename)s\t%(message)s"


[maeu]
api_key = ""
api_wait_second = 0.2

# For the active-vessels API
vessels.max_try = 3     # 1 = No retry, 2 = Retry once, ...
vessels.retry_second = 15
vessels.filename = "maeu_active_vessels_{}{}"

# For the vessel-schedules API
schedules.max_try = 3   # 1 = No retry, 2 = Retry once, ...
schedules.retry_second = 0.5
schedules.max_imo = -1  # Maximum number of imo to be processed, -1 = process all
schedules.carriers = ["MAEU", "SEAU", "SEJJ", "MCPU", "MAEI"]
schedules.data_range = "P12W"
schedules.filename = "maeu_vessel_schedules_{}{}"
