[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "sipher"
version = "1.0.0"
description = "To encrypt and decrypt message."
readme = "README.md"
requires-python = ">=3.6"
license = { text = "Apache License, Version 2.0" }
authors = [
    { name = "srg", email = "srg.code@pm.me" },
]
dependencies = [
    "pyperclip",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
keywords = [
    "sipher",
    "cipher",
    "morse",
    "encrypt",
    "decrypt"
]

[project.urls]
"Homepage" = "https://github.com/codesrg/sipher"
"Bug Tracker" = "https://github.com/codesrg/sipher/issues"

[project.scripts]
zenpass = "sipher.__main__:main"