[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tedtest"
version = "1.0.0"
authors = [
    { name="Tired Fox", email="zboehm104@gmail.com"}
]
description="Simple python testing framework"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "teddecor==1.0.1"
]

[project.scripts]
TEDTest = "tedtest.UnitTest.TEDTest:main"

[project.urls]
"Homepage" = "https://github.com/Tired-Fox/TEDTest"

