[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pylirecouleur"
version = "0.0.5"
authors = [
  { name="Marie-Pierre Brungard", email="lirecouleur@arkaline.fr" },
]
description = "Parse french texts into phonemes and syllables"
license = {file = "LICENSE.md"}
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Topic :: Education",
    "Natural Language :: French"
]
[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.setuptools.package-data]
"lirecouleur.appdata" = ["*.json"]

[project.urls]
"Homepage" = "https://framagit.org/arkaline/pylirecouleur"
"Bug Tracker" = "https://framagit.org/arkaline/pylirecouleur/issues"