[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "statemachine_decorator"
version = "2.0.1"
authors = [
  { name="Cmtheit", email="cmtheit@outlook.com" },
]
description = "This package offers a function which decorate any class with given states. And make sure any its object's state switch between them."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/chtheitmmmmm/statemachine"
"Bug Tracker" = "https://github.com/chtheitmmmmm/statemachine/issues"