[tool.poetry]
name = "ximea-py"
version = "4.27.02.1"
description = "XIMEA camera API"
authors = ["Jacob Feder <jacobsfeder@gmail.com>"]
readme = "README.md"
packages = [{include = "src/ximea"}]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
