[build-system]
requires = ["setuptools>=61.0", "BitVector"]
build-backend = "setuptools.build_meta"

[project]
name = "pythonRSC"
version = "0.0.1"
authors = [
  { name="Calastrophe", email="vmxoperation@proton.me" },
]
description = "An emulator for the RSC architecture written in Python."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Calastrophe/pyRSC"
"Bug Tracker" = "https://github.com/Calastrophe/pyRSC/issues"

