[tool.poetry]
name = "license-manager"
version = "0.2.2"
description = ""
authors = ["leaf <ncoder@126.com>"]

[tool.poetry.dependencies]
python = "^3.6"
fire = "^0.4.0"
pycryptodome = "^3.15.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[tool.poetry.scripts]
qxlicense = 'license_manager.main:main'