[tool.poetry]
name = "boerse-frankfurt-api"
version = "0.1.2"
description = ""
authors = ["Martin Marmsoler <martin.marmsoler@gmail.com>"]
readme = "Readme.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "=2.28.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
