[build-system]
requires = ["setuptools>=61.0", "Office365-REST-Python-Client>=2.3.14"]
build-backend = "setuptools.build_meta"

[project]
name = "onedrive-sharepoint"
version = "0.0.34"
authors = [
  { name="alphacpc", email="alphacpc@gmail.com" },
]
description = "Automation of some processes on office365"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
