[tool.poetry]
name = "aiovkapi"
version = "0.1.1"
description = "Библиотека для VK API с мимикрией под приложения VK"
authors = ["lordralinc <46781434+lordralinc@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/FBHTeam/aiovkapi"
documentation = "https://github.com/FBHTeam/aiovkapi/tree/master/docs/index.md"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/FBHTeam/aiovkapi/issues"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
aiohttp = ">=3.0,<4.0"
orjson = {version = ">=3.0,<4.0", optional = true}
pydantic = ">=1.0,<2.0"
aiofiles = ">=22.0"

[tool.poetry.dev-dependencies]
PyYAML = ">=5.4.1,<7.0"
pytest = ">=6.2.2"
flake8 = ">=3.8.4"
pyparsing = ">=2.4.7"
typing-extensions = ">=3.7.4"
pydantic = ">=1.8.1"
isort = ">=5.10.1"
autoflake = ">=1.7.7"
black = ">=22.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
