[tool.poetry]
name = "daily-event-logger"
version = "0.1.1"
description = ""
authors = ["Jeffrey Serio <hyperreal@fedoraproject.org>"]

[tool.poetry.dependencies]
python = "^3.10"
jsonschema = "^4.17.0"
rich = "^12.6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
