[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "daggerml-cli"
version = "0.0.3"
authors = [
  { name="DaggerML", email="engineering@daggerml.com" }
]
description = "DaggerML command line tool"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "daggerml==0.0.1",
  "typer[all]==0.4.0",
  "requests==2.27.1"
]

[project.scripts]
dml = "daggerml_cli.__init__:main"

[project.urls]
Homepage = "https://daggerml.com"
Documentation = "https://daggerml.com/docs"
Issues = "https://github.com/daggerml/daggerml-cli/issues"

[tool.setuptools.packages.find]
where = ["src"]
