[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "DSBA_Final"
version = "0.0.4"
dependencies = [
               "numpy",
                "pandas",
]

[tool.setuptools.package-data]
myModule = ["*.csv"]