[tool.poetry]
name = "aracnid-utils"
version = "1.0.2"
description = "Common custom utility functions"
authors = ["Jason Romano <aracnid@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/aracnid/aracnid-config"
keywords = ["python", "utils"]
packages = [{include = "aracnid_utils"}]

[tool.poetry.dependencies]
python = "^3.10"
aracnid-logger = "^1.0"
python-dateutil = "^2.8"
pytz = "^2022.2"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15"
pytest = "^7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-p no:warnings"
log_cli = true
log_cli_level = "DEBUG"
