[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "botstudio-sdk"
version = "0.0.25"
authors = [
  { name="Johan1us", email="info@botstudio.tech" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "rasa==2.8.31",
    "rasa-sdk==2.8.8",
    "google-api-python-client==2.65.0"
]

[project.urls]
"Homepage" = "https://github.com/botstudiotech/pip_package"
"Bug Tracker" = "https://github.com/botstudiotech/pip_package/issues"