[tool.poetry]
name = "cnextlib"
version = "0.7.0"
description = "cyc libraries for cyc-next-app"
authors = ["cycai company"]
license = "MIT"

packages = [
    { include = "cnextlib" },
]

[tool.poetry.dependencies]
python = ">=3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"