[tool.poetry]
authors = ["Jergu≈° Lejko <jergus.lejko@gmail.com>"]
description = ""
name = "datapac"
readme = "README.md"
version = "0.1.4"

[tool.poetry.scripts]
datapac = "datapac.cli:cli"

[tool.poetry.dependencies]
Jinja2 = "^3.1.2"
PyYAML = "^6.0"
boto3 = "^1.24.81"
click = "^8.1.3"
psycopg2 = "^2.9.3"
pydantic = "^1.10.2"
python = "^3.10"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
flake8-bugbear = "^22.7.1"
isort = "^5.10.1"
mypy = "^0.942"
pre-commit = "^2.20.0"
pytest = "^7.1.3"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.pytest.ini_options]
markers = ["override_settings"]

[tool.mypy]
ignore_missing_imports = true
no_site_packages = true

[tool.isort]
force_single_line = true
profile = "black"
