# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "privy-presidio-utils"
version = "0.0.62"
description = "Read the latest Real Python tutorials"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["nlp", "pii"]
dependencies = [
    "spacy>=3.2.0",
    "numpy>=1.20.2",
    "pandas>=1.2.4",
    "tqdm>=4.60.0",
    "haikunator>=2.1.0",
    "schwifty",
    "faker>=9.6.0",
    "scikit_learn",
    "flair",
    "stanza",
    "spacy_stanza",
    "sklearn_crfsuite",
    "pytest>=6.2.3",
    "presidio_analyzer",
    "presidio_anonymizer",
    "requests>=2.25.1",
    "xmltodict>=0.12.0",
    "python-dotenv",
]

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/benkilimnik/presidio-research"

[tool.bumpver]
current_version = "2022.1001-alpha"
version_pattern = "YYYY.BUILD[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]
"setup.py" = [
    "{version}",
    "{pep440_version}",
]
"README.md" = [
    "{version}",
    "{pep440_version}",
]

