[tool.poetry]
name = "vsui"
version = "0.1.0.1"
description = "Flask server and vue frontend for monitoring the progress of a python script."
authors = ["Matthew Pimblott <matthew.pimblott@diamond.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.2.2"
flask-socketio = "^5.3.1"
pyyaml = "^6.0"
gunicorn = "^20.1.0"
gevent = "^22.10.1"
gevent-websocket = "^0.10.1"

[tool.poetry.scripts]
vsui = "gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 module:vsui"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"