[tool.poetry]
name = "nhandd-test-poetry"
version = "1.0.0"
description = ""
authors = ["NhanDD <hp.duongducnhan@gmail.com>"]
readme = "README.md"
packages = [{include = "nhandd_test_poetry"}]

[tool.poetry.dependencies]
python = "^3.10"
termcolor = "^2.0.1"
pyfiglet = "^0.8.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
